name: Run Zerodha

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
    - uses: szenius/set-timezone@v1.0
      with:
         timezoneLinux: "Asia/Kolkata"
         timezoneMacos: "Asia/Kolkata"
         timezoneWindows: "Asia/Kolkata"
    - uses: actions/checkout@v2
    - name: create env file
      run: echo "${{ secrets.ENV }}" >> .env
    - run: npm install
    - run: npm start
